[package]
name = "exista_lib"
version = "0.1.0"
edition = "2021"



[dependencies]
serial = "0.4.0"
chrono = "0.4.23"
paho-mqtt = "0.12.0"
openssl = { version = "0.10", features = ["vendored"] }
json = "*"
once_cell = "1.17.1"
std-semaphore = "0.1.0"
os-sync = "0.3.3"